#!/bin/bash
docker run -it --rm -p 8080:8080 -e ODATA_SNOWFLAKE_ACCOUNT -e ODATA_SNOWFLAKE_USER -e ODATA_SNOWFLAKE_PASSWORD -e ODATA_SNOWFLAKE_DB -e ODATA_CLIENT_USER -e ODATA_CLIENT_PASSWORD inergy/snowflake-odata
